### ISSUE TITLE
Remove limit of 16 connections from web GUI

### ISSUE THREAD

**Issue by xathon** [sn0b4ll/aria2-onion-downloader#19]
Since the patch `downloader/removeconnlimit.patch` removes the limit of 16 from aria2, it should be possible to add a higher number of connections in the web GUI.

**Comment by sn0b4ll** [comment]
Hey @xathon, many thanks, I will look into it next week.

**Comment by sn0b4ll** [comment]
Hey @xathon, after reviewing your request I am afraid I can't help with that. This repo only bundles together aria2 + ariang + tor and since the patch only affects aria2, I am currently unaware of an option within ariang to disable the limit in the UI. If you really need more than 16 connections per server you could add downloads via the cli on the downloader pod. For that connect to the pod via `sudo docker exec -it aa78dd83ae11 /bin/bash` and afterwards add your download via `aria2c` with the `--max-connection-per-server=NUM` set to whichever number of connections you want.

You could also open this issue in the ariang repo: https://github.com/mayswind/AriaNg

**Comment by xathon** [comment]
Thanks for having a look! Next time I need it, I'll try the workaround, and I'll also make an issue in the repo you linked.

**Comment by sn0b4ll** [comment]
No problem, many thanks for bringing this to my attention :)
