### ISSUE TITLE
normal docker-compose.yaml and aria2

### ISSUE THREAD

**Issue by d4op** [sn0b4ll/aria2-onion-downloader#20]
i tried to docker-compose up -d local on debian.
entered the RPC secret but it doesnt connect to the RPC endpoint of aria2.
containers are up.

**Comment by d4op** [comment]
your index-helper branch works fine.

**Comment by sn0b4ll** [comment]
Hey @d4op, I experienced the same when I had darknet protection enabled on my router. Funny enough the router didn't block the tor traffic itself, but a script which searches for the fastest nodes. The downloader container than takes a long time to start / runs into a deadlock, because it can't fetch a file. That script is not reflected in the index-helper branch - so if that branch works for you, it is fine to use :)

But can you please check the container, e.g. checking the logfiles of docker-compose for the downloader and post them here? (See [here](https://docs.docker.com/reference/cli/docker/compose/logs/) if you are unaware how to fetch the logs)

**Comment by d4op** [comment]
can send you later when i am on pc. no problem.

**Comment by sn0b4ll** [comment]
Closing for now until the information is added.
