### ISSUE TITLE
error

### ISSUE THREAD

**Issue by clust4r** [sn0b4ll/aria2-onion-downloader#25]
time="2024-06-22T18:29:54+03:00" level=warning msg="C:\\Users\\Cluster\\OneDrive\\Desktop\\aria2-onion-downloader-main\\docker-compose.yml: `version` is obsolete"        error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.45/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Daria2-onion-downloader-main%22%3Atrue%7D%7D": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.

**Comment by sn0b4ll** [comment]
Hey @clust4r,

sorry for the late response and thanks for the hint, I removed the version information fixing the first warning line.

Sadly the error seems to be caused by your local installation of `docker` / `docker compose`. Please verify your installation and also try to run other `docker compose` projects.
